name: Fetch
on:
  workflow_dispatch:
  push:
  schedule:
    - cron:  '0 12 * * *'
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip3 install -r requirements.txt
      - run: python3 check-orebro.py
